In [1]:
import numpy as np

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.int16)

In [14]:
a.strides

(8, 2)

In [16]:
a.shape

(2, 4)

In [19]:
b = np.array([[1,2,3,4]])

In [22]:
b

array([[1, 2, 3, 4]])

In [23]:
np.ones((10,1), order='C').flags.f_contiguous

True

In [32]:
a.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [38]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int16)

In [39]:
a.transpose(0, 1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int16)

In [64]:
a.itemset(7, 9)

In [73]:
a = np.array([3, 4, 2, 1])
a.partition(0)
a

array([1, 4, 2, 3])