In [4]:
import scipy
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

from matplotlib import animation, rc
from IPython.display import HTML

### matplotlib pyplot

In [ ]:
# First set up the figure, the axis, and the plot element we want to animate
fig, ax = plt.subplots()

ax.set_xlim(( 0, 2))
ax.set_ylim((-2, 2))

line, = ax.plot([], [], lw=2)

In [ ]:
# initialization function: plot the background of each frame
def init():
    line.set_data([], [])
    return (line,)

In [ ]:
# animation function. This is called sequentially
def animate(i):
    x = np.linspace(0, 2, 1000)
    y = np.sin(2 * np.pi * (x - 0.01 * i))
    line.set_data(x, y)
    return (line,)

In [ ]:
# call the animator. blit=True means only re-draw the parts that have changed.
anim = animation.FuncAnimation(fig, animate, init_func=init,
                               frames=100, interval=20, blit=True)

In [ ]:
HTML(anim.to_html5_video())

In [ ]:
anim._repr_html_() is None

In [ ]:
rc('animation', html='html5')

In [ ]:
anim

### 如何理解 scipy.ndimage.correlate

In [2]:
from scipy.ndimage import correlate
import numpy as np

In [4]:
a = np.arange(10)
print(a)
correlate(np.arange(10), [1, 2], origin=-1)

[0 1 2 3 4 5 6 7 8 9]


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 27])

In [11]:
from scipy.ndimage import correlate1d
a = [0, 0, 1, 0, 0]
correlate(a, [1, 1, 1], origin=0)

array([0, 1, 1, 1, 0])

### 如何理解 axis

In [13]:
# https://zhuanlan.zhihu.com/p/25761406
import numpy as np

In [14]:
a = np.array([[1,2,3],[2,3,4],[3,4,9]])
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 9]])

In [17]:
# dimension, rank or axes is 2
np.ndim(a)

2

In [18]:
# 矩阵的秩 (rank) 是 3
np.linalg.matrix_rank(a)

3

In [21]:
# 定义一个 3D array
b = np.array([[[1,2,3,4],[1,3,4,5]],[[2,4,7,5],[8,4,3,5]],[[2,5,7,3],[1,5,3,7]]])
b

array([[[1, 2, 3, 4],
        [1, 3, 4, 5]],

       [[2, 4, 7, 5],
        [8, 4, 3, 5]],

       [[2, 5, 7, 3],
        [1, 5, 3, 7]]])

In [22]:
b.shape

(3, 2, 4)

In [32]:
# 在 axis 0 上进行 sum, 相当与对其他的 axis 上的元素, 在 axis 0 上 iterate 一遍并 sum
# 就将 axis 0 reduce 掉了, 原先的 shape (3,2,4) 变成了 (2,4)
b1 = b.sum(axis=0)
print(b1.shape)
b1

(2, 4)


array([[ 5, 11, 17, 12],
       [10, 12, 10, 17]])

In [41]:
# 同理, 在 axis 0 上 sort, 也即在其他 axis 上, 取 axis 0 的元素, 对其进行排序, 排序完成后的 array 中, 除 axis 0 上的 index
# 以外, 其他 axis 的 index 不变
b = np.array([[[5,2,3,4],[1,0,5,4]],[[2,4,7,5],[8,4,3,5]],[[2,5,7,3],[1,5,3,7]]])
b.sort(axis=0)
b

array([[[2, 2, 3, 3],
        [1, 0, 3, 4]],

       [[2, 4, 7, 4],
        [1, 4, 3, 5]],

       [[5, 5, 7, 5],
        [8, 5, 5, 7]]])

### 如何理解 numpy.rot90 中的 axis

In [2]:
import numpy as np

In [15]:
m = np.array([[[5,2,3,4],[1,0,5,4]],[[2,4,7,5],[8,4,3,5]],[[2,5,7,3],[1,5,3,7]]])
print(m.shape)
m

(3, 2, 4)


array([[[5, 2, 3, 4],
        [1, 0, 5, 4]],

       [[2, 4, 7, 5],
        [8, 4, 3, 5]],

       [[2, 5, 7, 3],
        [1, 5, 3, 7]]])

In [17]:
# 在 axis 0 和 1 构成的平面上旋转, 原先位置上的元素旋转到新的 array 后, 除了 axis 0 和 axis 1, 其他 axis 上的 index 不会改变
# 原先的 axis 0 变成 axis 1, 原先的 axis 1 变成 axis 0
m1 = np.rot90(m, 1, axes=(0,1))
print(m1.shape)
m1

(2, 3, 4)


array([[[1, 0, 5, 4],
        [8, 4, 3, 5],
        [1, 5, 3, 7]],

       [[5, 2, 3, 4],
        [2, 4, 7, 5],
        [2, 5, 7, 3]]])

In [19]:
n = np.array([[1, -1], [0, 0]])
n

array([[ 1, -1],
       [ 0,  0]])

In [22]:
# rot90 的 axes 参数是一个两元素的 tuple, 分别标记为 a1, a2, 表示旋转方向是从 axis a1 的正方向向 axis a2 的正方向旋转
# 这个例子中即从 axis 0 的正方向向 axis 1 的正方向旋转
np.rot90(n, 1, axes=(0,1))

array([[-1,  0],
       [ 1,  0]])